'use client'
import { Layout } from '@components'
import './globals.css'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'
import { song } from '@types'
import SongContext from '@context/songContext'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [songs, setSongs] = useState<song[]>([])

  useEffect(() => {
    const fetchSongs = async () => {
        const response = await fetch('/api/song');
        const data = await response.json()

        setSongs(data)

        console.log(data)
    }

    fetchSongs()
  }, [])


  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/idq4qqe.css" />
      </head>
      <SongContext.Provider value={songs}>
        <body className={inter.className} style={{ fontFamily: 'Aileron' }}>{children}</body>
      </SongContext.Provider>
    </html>
  )
}
